# import

In [3]:
# import tools
import sklearn.preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

import pandas as pd
import numpy as np

import acquire as a
import prepare as pre 


In [4]:
df = a.get_telco_data(a.get_connection)


In [5]:
df=pre.prep_telco(df)

In [6]:
train,validate,test = a.split_data(df)

In [70]:
def model_prep_stmt(train,validate,test):

    # keeping features columns
    keep_cols = ['senior_citizen',
                 'tenure',
                 'monthly_charges',
                 'tech_support_Yes',
                 'churn_Yes',
                 'customer_id']
    
    # making new data frames with only the features above
    train = train[keep_cols]
    validate = validate[keep_cols]
    test = test[keep_cols]
    
    # Split data into predicting variables (X) and target variable (y) and reset the index for each dataframe
    # creating x and y versions of train to remove the target variable
    train_x = train.drop(columns=['churn_Yes','customer_id'])
    train_y = train.churn_Yes

    # creating x and y versions of train to remove the target variable
    validate_x = validate.drop(columns=['churn_Yes','customer_id'])
    validate_y = validate.churn_Yes

   # creating x and y versions of train to remove the target variable
    test_x = test.drop(columns=['churn_Yes','customer_id'])
    test_y = test.churn_Yes
    
    return train_x, validate_x, test_x, train_y, validate_y, test_y
    

In [38]:
train_x, validate_x, test_x, train_y, validate_y, test_y = model_prep_stmt(train,validate,test)

In [39]:
def get_tree(train_x,validate_x,train_y,validate_y,md):
    
    # create classifier object
    clf = DecisionTreeClassifier(max_depth=md, random_state=42)
    
    #fit model on training data
    clf = clf.fit(train_x, train_y)
    
    # print result
    print(" Decision Tree ")
    print(f"Accuracy of Decision Tree on train data is {clf.score(train_x, train_y)}")
    print(f"Accuracy of Decision Tree on validate data is {clf.score(validate_x, validate_y)}")


In [40]:
get_tree(train_x,validate_x,train_y,validate_y,3)

 Decision Tree 
Accuracy of Decision Tree on train data is 0.7871475742951486
Accuracy of Decision Tree on validate data is 0.7748815165876777


In [41]:
def get_forest(train_x, validate_x, train_y, validate_y,md):
    
    '''get random forest accuracy on train and validate data'''

    # create model object and fit it to training data
    rf = RandomForestClassifier(max_depth=md, random_state=123)
    rf.fit(train_x,train_y)

    # print result
    print('Random Forest')
    print(f"Accuracy of Random Forest on train is {rf.score(train_x, train_y)}")
    print(f"Accuracy of Random Forest on validate is {rf.score(validate_x, validate_y)}")

In [42]:
get_forest(train_x, validate_x, train_y, validate_y,3)

Random Forest
Accuracy of Random Forest on train is 0.7962915925831852
Accuracy of Random Forest on validate is 0.7790284360189573


In [43]:
def get_reg(train_x, validate_x, train_y, validate_y):
    
    '''get logistic regression accuracy on train and validate data'''

    # create model object and fit it to the training data
    logit = LogisticRegression(solver='liblinear')
    logit.fit(train_x, train_y)

    # print result
    print('Logistic Regression')
    print(f"Accuracy of Logistic Regression on train is {logit.score(train_x, train_y)}")
    print(f"Accuracy of Logistic Regression on validate is {logit.score(validate_x, validate_y)}")


In [44]:
get_reg(train_x, validate_x, train_y, validate_y)

Logistic Regression
Accuracy of Logistic Regression on train is 0.7955295910591821
Accuracy of Logistic Regression on validate is 0.7808056872037915


In [45]:
def get_knn(train_x, validate_x, train_y, validate_y):
    
    '''get KNN accuracy on train and validate data'''

    # create model object and fit it to the training data
    knn = KNeighborsClassifier(n_neighbors=3, weights='uniform')
    knn.fit(train_x, train_y)

    # print results
    print('KNN')
    print(f"Accuracy of KNN on train is {knn.score(train_x, train_y)}")
    print(f"Accuracy of KNN on validate is {knn.score(validate_x, validate_y)}")


In [46]:
get_knn(train_x, validate_x, train_y, validate_y)

KNN
Accuracy of KNN on train is 0.858521717043434
Accuracy of KNN on validate is 0.7588862559241706


/usr/local/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
/usr/local/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. 

In [47]:
###########################

Model predictions

In [48]:

    # create model object and fit it to training data
    rf = RandomForestClassifier(max_depth=3, random_state=42)
    rf.fit(train_x,train_y)

    # print result
    print(' Random Forest')
    print(f"Accuracy of Random Forest on train is {rf.score(train_x, train_y)}")
    print(f"Accuracy of Random Forest on validate is {rf.score(validate_x, validate_y)}")
    print(f"Accuracy of Random Forest on test is {rf.score(test_x, test_y)}")

 Random Forest
Accuracy of Random Forest on train is 0.794259588519177
Accuracy of Random Forest on validate is 0.7819905213270142
Accuracy of Random Forest on test is 0.798862828713575


In [49]:

print(rf.feature_importances_)

[0.06504675 0.57609185 0.29624114 0.06262026]


In [50]:
y_pred = rf.predict(test_x)
y_pred

array([0, 1, 0, ..., 0, 0, 0], dtype=uint8)

In [51]:
y_pred_proba = rf.predict_proba(test_x)
y_pred_proba

array([[0.82058029, 0.17941971],
       [0.47105272, 0.52894728],
       [0.94389971, 0.05610029],
       ...,
       [0.59711349, 0.40288651],
       [0.94010375, 0.05989625],
       [0.78786792, 0.21213208]])

In [52]:
print(confusion_matrix(test_y, y_pred))

[[974  59]
 [224 150]]


# validate on out of sample

In [65]:
prob_pred = pd.DataFrame(y_pred_proba,y_pred)

In [66]:
prob_pred.rename(columns={0: 'Probability', 1: 'Predictions'}, inplace=True)

In [63]:
prob_pred = prob_pred.reset_index(drop=True)

In [67]:
prob_pred

Probability  Predictions
0      0.820580     0.179420
1      0.471053     0.528947
0      0.943900     0.056100
0      0.734836     0.265164
0      0.706496     0.293504
..          ...          ...
0      0.831784     0.168216
0      0.788553     0.211447
0      0.597113     0.402887
0      0.940104     0.059896
0      0.787868     0.212132

[1407 rows x 2 columns]

In [33]:
def get_best_model(train_x, validate_x, train_y, validate_y,md,test_x):
    '''get random forest accuracy on train and validate data'''

    # create model object and fit it to training data
    rf = RandomForestClassifier(max_depth=md, random_state=42)
    rf.fit(train_x,train_y)
    
    print("feature importance")
    print('\n')
    print(rf.feature_importances_)
    
    y_pred = rf.predict(test_x)
    
    y_pred_proba = rf.predict_proba(test_x)
    
    prob_pred = pd.DataFrame(y_pred_proba,y_pred)
    prob_pred.rename(columns={0: 'Probability', 1: 'Predictions'}, inplace=True)

    prob_pred = prob_pred.reset_index(drop=True)
    

    return prob_pred
    




In [35]:
prob_pred1 = get_best_model(train_x, validate_x, train_y, validate_y,5,test_x)

feature importance


[0.05970289 0.53675137 0.33394075 0.06960499]


In [57]:
prob_pred1

Probability  Predictions
0        0.893859     0.106141
1        0.486144     0.513856
2        0.979888     0.020112
3        0.738104     0.261896
4        0.730895     0.269105
...           ...          ...
1402     0.882581     0.117419
1403     0.802014     0.197986
1404     0.523183     0.476817
1405     0.976927     0.023073
1406     0.769359     0.230641

[1407 rows x 2 columns]